### ISSUE TITLE
Affine registration

### ISSUE THREAD

**Issue by xinkang** [bing-jian/gmmreg#3]
Hi Bing,

I want to use the API for register two 2D point sets.  One is a set of template points and the other is a set of detected points.  I want to get a best fit of the template points to the detected points while keep the shape of the template points.  My idea is to register the two point sets using affine transformation.  Would it possible just getting a affine transformation without GRBF or TPS deformation?  Or is there a way in your API that restrict the degree/amount of deformation?

Looking forwards to your kind prompt reply.  Thanks!

Best regards,
Ben

**Comment by bing-jian** [comment]
Ideally if the underlying transformation is affine or almost affine,  then the non-rigid part should be quite small, i.e. the GRBF or TPS coefficients returned in this case should be close to zero, given proper regularization.  What was your observation?

**Comment by xinkang** [comment]
I tried cpp_tps without setting any parameter.  The template point sets (called model in your code) were deformed severely to fit with the detected points and totally lost its shape.  To your information, the detected points include outliers and sometimes partial of the shape.  The underlying transformation should be an affine.  I did not set initial values for the coefficients.  How to enforce an affine registration?  What do you mean by "given proper regularization"?

**Comment by MelodyWang1314** [comment]
Dear Bing-jian:
I am so confused that data "fish_X_nohead" and "fish_y_notail"  have poor performance on point set registration. For what reason? weather should I set_ some good initial value?

Thanks!

![image](https://cloud.githubusercontent.com/assets/22960021/19562654/b33c96ea-970f-11e6-8eb1-eec1713b13f2.png)

@bing-jian

**Comment by bing-jian** [comment]
Melody, may I know how you tried to run the program?

**Comment by bing-jian** [comment]
Hi Liangzu,

Happy new year and thank you for the email.   Sorry for the late reply.  I
was on vacation and then a business trip.

As for your question,  are you using the MATLAB version?  It's recommended
to try the C++ or Python version as they were updated more recently.   For
the configuration,  can you please also try setting config.normalize = 1
instead of config.normalize = 0

https://github.com/bing-jian/gmmreg/blob/master/MATLAB/initialize_config.m#L12

Additionally,  for performance evaluation in the setting of point set
registration,  I prefer using recall vs threshold to comparing the absolute
error metric, because when the point wise error is small enough they can be
easily paired and the slight error differences here do not matter.

Thanks,
Bing
